version: '3.5'

services:
  db_edu:
    container_name: PGdb
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=root"
      - "POSTGRES_USER=admin"
    image: postgres:14.10-alpine
